using Explorify.Domain.Entities;

using Microsoft.EntityFrameworkCore;

namespace Explorify.Persistence.Seeding.Seeders;

public class CountriesSeeder : ISeeder
{
    private readonly List<Country> _countries;

    public CountriesSeeder()
    {
        _countries =
            [
                new() { Name = "Afghanistan" },
                new() { Name = "Albania" },
                new() { Name = "Algeria" },
                new() { Name = "Andorra" },
                new() { Name = "Angola" },
                new() { Name = "Antigua and Barbuda" },
                new() { Name = "Argentina" },
                new() { Name = "Armenia" },
                new() { Name = "Australia" },
                new() { Name = "Austria" },
                new() { Name = "Azerbaijan" },
                new() { Name = "Bahamas" },
                new() { Name = "Bahrain" },
                new() { Name = "Bangladesh" },
                new() { Name = "Barbados" },
                new() { Name = "Belarus" },
                new() { Name = "Belgium" },
                new() { Name = "Belize" },
                new() { Name = "Benin" },
                new() { Name = "Bhutan" },
                new() { Name = "Bolivia" },
                new() { Name = "Bosnia and Herzegovina" },
                new() { Name = "Botswana" },
                new() { Name = "Brazil" },
                new() { Name = "Brunei" },
                new() { Name = "Bulgaria" },
                new() { Name = "Burkina Faso" },
                new() { Name = "Burundi" },
                new() { Name = "Cabo Verde" },
                new() { Name = "Cambodia" },
                new() { Name = "Cameroon" },
                new() { Name = "Canada" },
                new() { Name = "Central African Republic" },
                new() { Name = "Chad" },
                new() { Name = "Chile" },
                new() { Name = "China" },
                new() { Name = "Colombia" },
                new() { Name = "Comoros" },
                new() { Name = "Congo (Brazzaville)" },
                new() { Name = "Congo (Kinshasa)" },
                new() { Name = "Costa Rica" },
                new() { Name = "Côte d’Ivoire" },
                new() { Name = "Croatia" },
                new() { Name = "Cuba" },
                new() { Name = "Cyprus" },
                new() { Name = "Czech Republic" },
                new() { Name = "Denmark" },
                new() { Name = "Djibouti" },
                new() { Name = "Dominica" },
                new() { Name = "Dominican Republic" },
                new() { Name = "Ecuador" },
                new() { Name = "Egypt" },
                new() { Name = "El Salvador" },
                new() { Name = "Equatorial Guinea" },
                new() { Name = "Eritrea" },
                new() { Name = "Estonia" },
                new() { Name = "Eswatini" },
                new() { Name = "Ethiopia" },
                new() { Name = "Fiji" },
                new() { Name = "Finland" },
                new() { Name = "France" },
                new() { Name = "Gabon" },
                new() { Name = "Gambia" },
                new() { Name = "Georgia" },
                new() { Name = "Germany" },
                new() { Name = "Ghana" },
                new() { Name = "Greece" },
                new() { Name = "Grenada" },
                new() { Name = "Guatemala" },
                new() { Name = "Guinea" },
                new() { Name = "Guinea-Bissau" },
                new() { Name = "Guyana" },
                new() { Name = "Haiti" },
                new() { Name = "Honduras" },
                new() { Name = "Hungary" },
                new() { Name = "Iceland" },
                new() { Name = "India" },
                new() { Name = "Indonesia" },
                new() { Name = "Iran" },
                new() { Name = "Iraq" },
                new() { Name = "Ireland" },
                new() { Name = "Israel" },
                new() { Name = "Italy" },
                new() { Name = "Jamaica" },
                new() { Name = "Japan" },
                new() { Name = "Jordan" },
                new() { Name = "Kazakhstan" },
                new() { Name = "Kenya" },
                new() { Name = "Kiribati" },
                new() { Name = "Korea, North" },
                new() { Name = "Korea, South" },
                new() { Name = "Kosovo" },
                new() { Name = "Kuwait" },
                new() { Name = "Kyrgyzstan" },
                new() { Name = "Laos" },
                new() { Name = "Latvia" },
                new() { Name = "Lebanon" },
                new() { Name = "Lesotho" },
                new() { Name = "Liberia" },
                new() { Name = "Libya" },
                new() { Name = "Liechtenstein" },
                new() { Name = "Lithuania" },
                new() { Name = "Luxembourg" },
                new() { Name = "Madagascar" },
                new() { Name = "Malawi" },
                new() { Name = "Malaysia" },
                new() { Name = "Maldives" },
                new() { Name = "Mali" },
                new() { Name = "Malta" },
                new() { Name = "Marshall Islands" },
                new() { Name = "Mauritania" },
                new() { Name = "Mauritius" },
                new() { Name = "Mexico" },
                new() { Name = "Micronesia" },
                new() { Name = "Moldova" },
                new() { Name = "Monaco" },
                new() { Name = "Mongolia" },
                new() { Name = "Montenegro" },
                new() { Name = "Morocco" },
                new() { Name = "Mozambique" },
                new() { Name = "Myanmar" },
                new() { Name = "Namibia" },
                new() { Name = "Nauru" },
                new() { Name = "Nepal" },
                new() { Name = "Netherlands" },
                new() { Name = "New Zealand" },
                new() { Name = "Nicaragua" },
                new() { Name = "Niger" },
                new() { Name = "Nigeria" },
                new() { Name = "North Macedonia" },
                new() { Name = "Norway" },
                new() { Name = "Oman" },
                new() { Name = "Pakistan" },
                new() { Name = "Palau" },
                new() { Name = "Panama" },
                new() { Name = "Papua New Guinea" },
                new() { Name = "Paraguay" },
                new() { Name = "Peru" },
                new() { Name = "Philippines" },
                new() { Name = "Poland" },
                new() { Name = "Portugal" },
                new() { Name = "Qatar" },
                new() { Name = "Romania" },
                new() { Name = "Russia" },
                new() { Name = "Rwanda" },
                new() { Name = "Saint Kitts and Nevis" },
                new() { Name = "Saint Lucia" },
                new() { Name = "Saint Vincent and the Grenadines" },
                new() { Name = "Samoa" },
                new() { Name = "San Marino" },
                new() { Name = "Sao Tome and Principe" },
                new() { Name = "Saudi Arabia" },
                new() { Name = "Senegal" },
                new() { Name = "Serbia" },
                new() { Name = "Seychelles" },
                new() { Name = "Sierra Leone" },
                new() { Name = "Singapore" },
                new() { Name = "Slovakia" },
                new() { Name = "Slovenia" },
                new() { Name = "Solomon Islands" },
                new() { Name = "Somalia" },
                new() { Name = "South Africa" },
                new() { Name = "South Korea" },
                new() { Name = "South Sudan" },
                new() { Name = "Spain" },
                new() { Name = "Sri Lanka" },
                new() { Name = "Sudan" },
                new() { Name = "Suriname" },
                new() { Name = "Sweden" },
                new() { Name = "Switzerland" },
                new() { Name = "Syria" },
                new() { Name = "Taiwan" },
                new() { Name = "Tajikistan" },
                new() { Name = "Tanzania" },
                new() { Name = "Thailand" },
                new() { Name = "Timor-Leste" },
                new() { Name = "Togo" },
                new() { Name = "Tonga" },
                new() { Name = "Trinidad and Tobago" },
                new() { Name = "Tunisia" },
                new() { Name = "Turkey" },
                new() { Name = "Turkmenistan" },
                new() { Name = "Tuvalu" },
                new() { Name = "Uganda" },
                new() { Name = "Ukraine" },
                new() { Name = "United Arab Emirates" },
                new() { Name = "United Kingdom" },
                new() { Name = "United States" },
                new() { Name = "Uruguay" },
                new() { Name = "Uzbekistan" },
                new() { Name = "Vanuatu" },
                new() { Name = "Vatican City" },
                new() { Name = "Venezuela" },
                new() { Name = "Vietnam" },
                new() { Name = "Yemen" },
                new() { Name = "Zambia" },
                new() { Name = "Zimbabwe" }
            ];
    }

    public async Task SeedAsync(
        ExplorifyDbContext dbContext,
        IServiceProvider serviceProvider)
    {
        if (await dbContext.Countries.AnyAsync())
        {
            return;
        }

        await dbContext.Countries.AddRangeAsync(_countries);
    }
}
